#ifndef VELK_API_OBJECT_REF_H
#define VELK_API_OBJECT_REF_H

#include <velk/api/velk.h>
#include <velk/interface/intf_any.h>
#include <velk/interface/intf_object_ref.h>
#include <velk/interface/types.h>

namespace velk {

/**
 * @brief State-struct type for object reference properties.
 *
 * Lives in the State struct generated by VELK_INTERFACE for ObjectRef properties.
 * Holds an IObjectRef::Ptr that the property system fills with an ObjectRefImpl
 * on first access via PropBind::createRef.
 */
class ObjectRef
{
public:
    ObjectRef() = default;
    ObjectRef(IObjectRef::Ptr existing) : any_(std::move(existing)) {}

    explicit operator bool() const noexcept { return any_ != nullptr; }
    bool operator==(const ObjectRef& other) const noexcept { return any_ == other.any_; }
    bool operator!=(const ObjectRef& other) const noexcept { return any_ != other.any_; }

    /** @brief Implicit conversion to IObjectRef::Ptr. */
    operator IObjectRef::Ptr() noexcept { return any_; }
    operator IObjectRef::ConstPtr() const noexcept { return any_; }
    /** @brief Implicit conversion to IAny::Ptr. */
    operator IAny::Ptr() noexcept { return any_; }
    operator IAny::ConstPtr() const noexcept { return any_; }
    /** @brief Move assignment. */
    ObjectRef& operator=(IObjectRef::Ptr&& v) noexcept
    {
        any_ = std::move(v);
        return *this;
    }

    /** @brief Returns the referenced object, or nullptr if empty/expired. */
    IObject::Ptr get() const { return any_ ? any_->get_object() : nullptr; }

    /** @brief Returns the referenced object cast to interface T, or nullptr. */
    template <class T>
    typename T::Ptr get() const
    {
        return any_ ? interface_pointer_cast<T>(any_->get_object()) : nullptr;
    }

    /** @brief Sets the referenced object. */
    ReturnValue set(const IObject::Ptr& obj) { return any_ ? any_->set_object(obj) : ReturnValue::Fail; }

    /** @brief Returns true if this ref holds a strong (owning) reference. */
    bool is_owning() const { return any_ ? any_->is_owning() : true; }

    /** @brief Sets the owning mode. */
    ReturnValue set_owning(bool owning) { return any_ ? any_->set_owning(owning) : ReturnValue::Fail; }

    /** @brief Sets the interface constraint. set() will reject objects that don't implement T. */
    template <class T>
    void set_constraint()
    {
        if (any_) {
            any_->set_constraint(T::UID);
        }
    }

    /** @brief Returns the constraint UID, or empty Uid if unconstrained. */
    Uid constraint_uid() const { return any_ ? any_->constraint_uid() : Uid{}; }

private:
    IObjectRef::Ptr any_;
};

/** @brief Creates an empty owning ObjectRef. */
inline ObjectRef create_object_ref()
{
    return ObjectRef(instance().create_object_ref());
}

/** @brief Creates an owning ObjectRef that references @p obj. */
inline ObjectRef create_object_ref(const IObject::Ptr& obj)
{
    auto ref = create_object_ref();
    ref.set(obj);
    return ref;
}

/** @brief Creates an empty non-owning (weak) ObjectRef. */
inline ObjectRef create_weak_object_ref()
{
    auto ref = create_object_ref();
    ref.set_owning(false);
    return ref;
}

/** @brief Creates a non-owning (weak) ObjectRef that references @p obj. */
inline ObjectRef create_weak_object_ref(const IObject::Ptr& obj)
{
    auto ref = create_object_ref();
    ref.set(obj);
    ref.set_owning(false);
    return ref;
}

} // namespace velk

#endif // VELK_API_OBJECT_REF_H
