#ifndef VELK_API_VARIANT_H
#define VELK_API_VARIANT_H

#include <velk/api/velk.h>
#include <velk/interface/intf_any.h>
#include <velk/interface/intf_variant.h>
#include <velk/interface/types.h>

namespace velk {

/**
 * @brief State-struct type for variant (typeless) properties.
 *
 * Lives in the State struct generated by VELK_INTERFACE for Variant properties.
 * Holds an IAny::Ptr that the property system fills with a VariantImpl on first
 * access via PropBind::createRef. Provides typed get/set convenience methods.
 */
class Variant
{
public:
    Variant() = default;
    Variant(IVariant::Ptr existing) : any_(std::move(existing)) {};

    explicit operator bool() const noexcept { return any_ != nullptr; }
    bool operator==(const Variant& other) const noexcept { return any_ == other.any_; }
    bool operator!=(const Variant& other) const noexcept { return any_ != other.any_; }

    /** @brief Implicit conversion to IVariant::Ptr. */
    operator IVariant::Ptr() noexcept { return any_; }
    operator IVariant::ConstPtr() const noexcept { return any_; }
    /** @brief Implicit conversion to IAny::Ptr. */
    operator IAny::Ptr() noexcept { return any_; }
    operator IAny::ConstPtr() const noexcept { return any_; }
    /** @brief Move assignment. */
    Variant& operator=(IVariant::Ptr&& v) noexcept
    {
        any_ = std::move(v);
        return *this;
    }

    /** @brief Returns the stored value as type T, or default-constructed T on failure. */
    template <class T>
    T get() const
    {
        T value{};
        if (any_) {
            any_->get_data(&value, sizeof(T), type_uid<T>());
        }
        return value;
    }

    /** @brief Sets the stored value to the given typed value. */
    template <class T>
    ReturnValue set(const T& value)
    {
        return any_ ? any_->set_data(&value, sizeof(T), type_uid<T>()) : ReturnValue::Fail;
    }

    /** @brief Returns the UID of the currently stored type, or empty Uid if empty. */
    Uid stored_type() const { return any_ ? any_->stored_type() : Uid{}; }

    /** @brief Returns true if the stored value can be converted to the given type. */
    bool can_convert_to(Uid type) const
    {
        auto* v = interface_cast<IVariant>(any_);
        return v && v->can_convert_to(type);
    }

private:
    /** @brief The backing IAny pointer. Filled by the property system via PropBind::createRef. */
    IVariant::Ptr any_;
};

} // namespace velk

#endif // VELK_API_VARIANT_H
